const data = [
    { pilots: "1", ISO3: "AGO", country:"Angola" },
    { pilots: "1", ISO3: "AUS", country:"Australia" },
    { pilots: "1", ISO3: "BRA", country:"Brazil" },
    { pilots: "1", ISO3: "CYP", country:"Cyprus" },
    { pilots: "1", ISO3: "DNK", country:"Denmark" },
    { pilots: "1", ISO3: "FIN", country:"Finland" },
    { pilots: "1", ISO3: "DEU", country:"Germany" },
    { pilots: "1", ISO3: "IND", country:"India" },
    { pilots: "1", ISO3: "KEN", country:"Kenya" },
    { pilots: "1", ISO3: "LVA", country:"Latvia" },
    { pilots: "1", ISO3: "MWI", country:"Malawi" },
    { pilots: "1", ISO3: "NAM", country:"Namibia" },
    { pilots: "1", ISO3: "NGA", country:"Nigeria" },
    { pilots: "1", ISO3: "NOR", country:"Norway" },
    { pilots: "1", ISO3: "PAN", country:"Panama" },
    { pilots: "1", ISO3: "PHL", country:"Philippines" },
    { pilots: "1", ISO3: "RWA", country:"Rwanda" },
    { pilots: "1", ISO3: "SEN", country:"Senegal" },
    { pilots: "1", ISO3: "ZAF", country:"South Africa" },
    { pilots: "1", ISO3: "SWE", country:"Sweden" },
    { pilots: "1", ISO3: "CHE", country:"Switzerland" },
    { pilots: "1", ISO3: "ARE", country:"UAE" },
    { pilots: "1", ISO3: "GBR", country:"UK" },
    { pilots: "1", ISO3: "USA", country:"United States" },
  ];

  export default data;
