const data = [
    { pilots: "1", ISO3: "ARG", country:"Argentina" }, 
    { pilots: "1", ISO3: "CAN", country:"Canada" }, 
    { pilots: "1", ISO3: "CHL", country:"Chile" }, 
    { pilots: "1", ISO3: "CRI", country:"Costa Rica" }, 
    { pilots: "1", ISO3: "HRV", country:"Croatia" }, 
    { pilots: "1", ISO3: "IND", country:"India" },   
    { pilots: "1", ISO3: "ITA", country:"Italy" },    
    { pilots: "1", ISO3: "LSO", country:"Lesotho" }, 
    { pilots: "1", ISO3: "LUX", country:"Luxembourg" },     
    { pilots: "1", ISO3: "MWI", country:"Malawi" },
    { pilots: "1", ISO3: "MDV", country:"Maldives" }, 
    { pilots: "1", ISO3: "MLI", country:"Mali" }, 
    { pilots: "1", ISO3: "NZL", country:"New Zealand" }, 
    { pilots: "1", ISO3: "POL", country:"Poland" },    
    { pilots: "1", ISO3: "SEN", country:"Senegal" }, 
    { pilots: "1", ISO3: "ZAF", country:"South Africa" }, 
    { pilots: "1", ISO3: "ESP", country:"Spain" }, 
    { pilots: "1", ISO3: "SWE", country:"Sweden" }, 
    { pilots: "1", ISO3: "TGO", country:"Switzerland" },
    { pilots: "1", ISO3: "TZA", country:"Tanzania" },   
    { pilots: "1", ISO3: "TGO", country:"Togo" },
    { pilots: "1", ISO3: "UKR", country:"Ukraine" }, 
    { pilots: "1", ISO3: "ARE", country:"UAE" }, 
    { pilots: "1", ISO3: "GBR", country:"United Kingdom" },
    { pilots: "1", ISO3: "USA", country:"United States" },
    { pilots: "1", ISO3: "ZWE", country:"Zimbabwe" }, 
  ];

  export default data;
