const data = [
    { pilots: "1", ISO3: "ARG", country:"Argentina" },   
    { pilots: "1", ISO3: "AUS", country:"Australia" },   
    { pilots: "1", ISO3: "BEL", country:"Belgium" },   
    { pilots: "1", ISO3: "BRA", country:"Brazil" },   
    { pilots: "1", ISO3: "BGR", country:"Bulgaria" },   
    { pilots: "1", ISO3: "CAN", country:"Canada" }, 
    { pilots: "1", ISO3: "CHN", country:"China" },
    { pilots: "1", ISO3: "COL", country:"Colombia" },  
    { pilots: "1", ISO3: "CZE", country:"Czechia" },  
    { pilots: "1", ISO3: "EST", country:"Estonia" }, 
    { pilots: "1", ISO3: "FRA", country:"France" }, 
    { pilots: "1", ISO3: "DEU", country:"Germany" }, 
    { pilots: "1", ISO3: "GHA", country:"Ghana" }, 
    { pilots: "1", ISO3: "GIB", country:"Gibraltar" }, 
    { pilots: "1", ISO3: "GRC", country:"Greece" },  
    { pilots: "1", ISO3: "HUN", country:"Hungary" }, 
    { pilots: "1", ISO3: "IND", country:"India" },
    { pilots: "1", ISO3: "IDN", country:"Indonesia" },  
    { pilots: "1", ISO3: "ITA", country:"Italy" },  
    { pilots: "1", ISO3: "KEN", country:"Kenya" },  
    { pilots: "1", ISO3: "LVA", country:"Latvia" },  
    { pilots: "1", ISO3: "MYS", country:"Malaysia" },  
    { pilots: "1", ISO3: "MLI", country:"Mali" },
    { pilots: "1", ISO3: "MEX", country:"Mexico" },
    { pilots: "1", ISO3: "MAR", country:"Morocco" }, 
    { pilots: "1", ISO3: "NLD", country:"Netherlands" },  
    { pilots: "1", ISO3: "NGA", country:"Nigeria" }, 
    { pilots: "1", ISO3: "PNG", country:"Papua New Guinea" }, 
    { pilots: "1", ISO3: "PHL", country:"Philippines" },  
    { pilots: "1", ISO3: "POL", country:"Poland" },  
    { pilots: "1", ISO3: "PRI", country:"Puerto Rico" }, 
    { pilots: "1", ISO3: "SEN", country:"Senegal" },        
    { pilots: "1", ISO3: "ZAF", country:"South Africa" },   
    { pilots: "1", ISO3: "ESP", country:"Spain" },   
    { pilots: "1", ISO3: "SWE", country:"Sweden" }, 
    { pilots: "1", ISO3: "CHE", country:"Switzerland" }, 
    { pilots: "1", ISO3: "UGA", country:"Uganda" }, 
    { pilots: "1", ISO3: "GBR", country:"United Kingdom" },   
    { pilots: "1", ISO3: "USA", country:"United States" },
  ];

  export default data;
